### ISSUE TITLE
[Fix] : 프로젝트 내 Service의 return 객체를 모두 Dto로 변경 

### ISSUE THREAD

**Issue by suhanBae1201** [NHN-YesAladin/yesaladin_shop#68]
## 수정할 버그
- [ ] 프로젝트 내 Service의 return 객체를 모두 Dto로 변경 
   - [x] 학현
   - [x] 수한
   - [x] 민지
   - [ ] 선홍
   - [ ] 예린
   - [x] 수정
   - [x] 홍대 

## 참고사항
Open In View(=OSIV) 를 끄는게 프로그램에 옳다고 판단하여 Spring boot내 default 값인 true를 false로 변경할 예정이니 
모든 팀원 분들은 위 수정사항에 대해 변경 후에 체크 부탁드립니다.
(안 고치면 버그납니다 <- 버그 태그 단 이유)

**Comment by alanhakhyeonsong** [comment]
~~`CommandXxxService`의 경우 변경했고, `QueryXxxService`의 경우 다른 service들에서 사용하고 있어서 변경하지 않았습니다. `QueryXxxController`에서 직접 해당 `QueryXxxService`를 사용하는 경우엔 해당 메소드를 추가로 만들도록 할게요.~~

변경 완료했습니다.

**Comment by suhanBae1201** [comment]
Feature/#68 return dto변경 및 JavaDoc 보완 #79
